version: '3.7'

services:
  app:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - "./docker-test-output:/app/OnnxStack.IntegrationTests/bin/Debug/net7.0/images"